// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/admin/analytics_admin_service.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsAdminService_ListTariffs_FullMethodName        = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/ListTariffs"
	AnalyticsAdminService_CreateTariff_FullMethodName       = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/CreateTariff"
	AnalyticsAdminService_UpdateTariff_FullMethodName       = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/UpdateTariff"
	AnalyticsAdminService_SetDefaultTariff_FullMethodName   = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/SetDefaultTariff"
	AnalyticsAdminService_AssignVendorTariff_FullMethodName = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/AssignVendorTariff"
	AnalyticsAdminService_GetVendorTariff_FullMethodName    = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/GetVendorTariff"
	AnalyticsAdminService_GetUserDashboard_FullMethodName   = "/github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService/GetUserDashboard"
)

// AnalyticsAdminServiceClient is the client API for AnalyticsAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsAdminServiceClient interface {
	ListTariffs(ctx context.Context, in *ListTariffsRequest, opts ...grpc.CallOption) (*ListTariffsResponse, error)
	CreateTariff(ctx context.Context, in *CreateTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error)
	UpdateTariff(ctx context.Context, in *UpdateTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error)
	SetDefaultTariff(ctx context.Context, in *SetDefaultTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error)
	AssignVendorTariff(ctx context.Context, in *AssignVendorTariffRequest, opts ...grpc.CallOption) (*VendorTariffResponse, error)
	GetVendorTariff(ctx context.Context, in *GetVendorTariffRequest, opts ...grpc.CallOption) (*VendorTariffResponse, error)
	GetUserDashboard(ctx context.Context, in *GetUserDashboardRequest, opts ...grpc.CallOption) (*GetUserDashboardResponse, error)
}

type analyticsAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsAdminServiceClient(cc grpc.ClientConnInterface) AnalyticsAdminServiceClient {
	return &analyticsAdminServiceClient{cc}
}

func (c *analyticsAdminServiceClient) ListTariffs(ctx context.Context, in *ListTariffsRequest, opts ...grpc.CallOption) (*ListTariffsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTariffsResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_ListTariffs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsAdminServiceClient) CreateTariff(ctx context.Context, in *CreateTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TariffResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_CreateTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsAdminServiceClient) UpdateTariff(ctx context.Context, in *UpdateTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TariffResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_UpdateTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsAdminServiceClient) SetDefaultTariff(ctx context.Context, in *SetDefaultTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TariffResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_SetDefaultTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsAdminServiceClient) AssignVendorTariff(ctx context.Context, in *AssignVendorTariffRequest, opts ...grpc.CallOption) (*VendorTariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorTariffResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_AssignVendorTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsAdminServiceClient) GetVendorTariff(ctx context.Context, in *GetVendorTariffRequest, opts ...grpc.CallOption) (*VendorTariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorTariffResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_GetVendorTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsAdminServiceClient) GetUserDashboard(ctx context.Context, in *GetUserDashboardRequest, opts ...grpc.CallOption) (*GetUserDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDashboardResponse)
	err := c.cc.Invoke(ctx, AnalyticsAdminService_GetUserDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsAdminServiceServer is the server API for AnalyticsAdminService service.
// All implementations must embed UnimplementedAnalyticsAdminServiceServer
// for forward compatibility.
type AnalyticsAdminServiceServer interface {
	ListTariffs(context.Context, *ListTariffsRequest) (*ListTariffsResponse, error)
	CreateTariff(context.Context, *CreateTariffRequest) (*TariffResponse, error)
	UpdateTariff(context.Context, *UpdateTariffRequest) (*TariffResponse, error)
	SetDefaultTariff(context.Context, *SetDefaultTariffRequest) (*TariffResponse, error)
	AssignVendorTariff(context.Context, *AssignVendorTariffRequest) (*VendorTariffResponse, error)
	GetVendorTariff(context.Context, *GetVendorTariffRequest) (*VendorTariffResponse, error)
	GetUserDashboard(context.Context, *GetUserDashboardRequest) (*GetUserDashboardResponse, error)
	mustEmbedUnimplementedAnalyticsAdminServiceServer()
}

// UnimplementedAnalyticsAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsAdminServiceServer struct{}

func (UnimplementedAnalyticsAdminServiceServer) ListTariffs(context.Context, *ListTariffsRequest) (*ListTariffsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTariffs not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) CreateTariff(context.Context, *CreateTariffRequest) (*TariffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTariff not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) UpdateTariff(context.Context, *UpdateTariffRequest) (*TariffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTariff not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) SetDefaultTariff(context.Context, *SetDefaultTariffRequest) (*TariffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultTariff not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) AssignVendorTariff(context.Context, *AssignVendorTariffRequest) (*VendorTariffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignVendorTariff not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) GetVendorTariff(context.Context, *GetVendorTariffRequest) (*VendorTariffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendorTariff not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) GetUserDashboard(context.Context, *GetUserDashboardRequest) (*GetUserDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDashboard not implemented")
}
func (UnimplementedAnalyticsAdminServiceServer) mustEmbedUnimplementedAnalyticsAdminServiceServer() {}
func (UnimplementedAnalyticsAdminServiceServer) testEmbeddedByValue()                               {}

// UnsafeAnalyticsAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsAdminServiceServer will
// result in compilation errors.
type UnsafeAnalyticsAdminServiceServer interface {
	mustEmbedUnimplementedAnalyticsAdminServiceServer()
}

func RegisterAnalyticsAdminServiceServer(s grpc.ServiceRegistrar, srv AnalyticsAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsAdminService_ServiceDesc, srv)
}

func _AnalyticsAdminService_ListTariffs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTariffsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).ListTariffs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_ListTariffs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).ListTariffs(ctx, req.(*ListTariffsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsAdminService_CreateTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).CreateTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_CreateTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).CreateTariff(ctx, req.(*CreateTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsAdminService_UpdateTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).UpdateTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_UpdateTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).UpdateTariff(ctx, req.(*UpdateTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsAdminService_SetDefaultTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).SetDefaultTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_SetDefaultTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).SetDefaultTariff(ctx, req.(*SetDefaultTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsAdminService_AssignVendorTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignVendorTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).AssignVendorTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_AssignVendorTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).AssignVendorTariff(ctx, req.(*AssignVendorTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsAdminService_GetVendorTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).GetVendorTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_GetVendorTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).GetVendorTariff(ctx, req.(*GetVendorTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsAdminService_GetUserDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsAdminServiceServer).GetUserDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsAdminService_GetUserDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsAdminServiceServer).GetUserDashboard(ctx, req.(*GetUserDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsAdminService_ServiceDesc is the grpc.ServiceDesc for AnalyticsAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService",
	HandlerType: (*AnalyticsAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTariffs",
			Handler:    _AnalyticsAdminService_ListTariffs_Handler,
		},
		{
			MethodName: "CreateTariff",
			Handler:    _AnalyticsAdminService_CreateTariff_Handler,
		},
		{
			MethodName: "UpdateTariff",
			Handler:    _AnalyticsAdminService_UpdateTariff_Handler,
		},
		{
			MethodName: "SetDefaultTariff",
			Handler:    _AnalyticsAdminService_SetDefaultTariff_Handler,
		},
		{
			MethodName: "AssignVendorTariff",
			Handler:    _AnalyticsAdminService_AssignVendorTariff_Handler,
		},
		{
			MethodName: "GetVendorTariff",
			Handler:    _AnalyticsAdminService_GetVendorTariff_Handler,
		},
		{
			MethodName: "GetUserDashboard",
			Handler:    _AnalyticsAdminService_GetUserDashboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin/analytics_admin_service.proto",
}
