// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/admin/analytics_admin_service.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTariffsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTariffsRequest) Reset() {
	*x = ListTariffsRequest{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTariffsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTariffsRequest) ProtoMessage() {}

func (x *ListTariffsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTariffsRequest.ProtoReflect.Descriptor instead.
func (*ListTariffsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{0}
}

type ListTariffsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tariffs       []*Tariff              `protobuf:"bytes,1,rep,name=tariffs,proto3" json:"tariffs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTariffsResponse) Reset() {
	*x = ListTariffsResponse{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTariffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTariffsResponse) ProtoMessage() {}

func (x *ListTariffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTariffsResponse.ProtoReflect.Descriptor instead.
func (*ListTariffsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListTariffsResponse) GetTariffs() []*Tariff {
	if x != nil {
		return x.Tariffs
	}
	return nil
}

type CreateTariffRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CommissionPercent string                 `protobuf:"bytes,2,opt,name=commission_percent,json=commissionPercent,proto3" json:"commission_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTariffRequest) Reset() {
	*x = CreateTariffRequest{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTariffRequest) ProtoMessage() {}

func (x *CreateTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTariffRequest.ProtoReflect.Descriptor instead.
func (*CreateTariffRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTariffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTariffRequest) GetCommissionPercent() string {
	if x != nil {
		return x.CommissionPercent
	}
	return ""
}

type UpdateTariffRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TariffId          int64                  `protobuf:"varint,1,opt,name=tariff_id,json=tariffId,proto3" json:"tariff_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommissionPercent string                 `protobuf:"bytes,3,opt,name=commission_percent,json=commissionPercent,proto3" json:"commission_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateTariffRequest) Reset() {
	*x = UpdateTariffRequest{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTariffRequest) ProtoMessage() {}

func (x *UpdateTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTariffRequest.ProtoReflect.Descriptor instead.
func (*UpdateTariffRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTariffRequest) GetTariffId() int64 {
	if x != nil {
		return x.TariffId
	}
	return 0
}

func (x *UpdateTariffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTariffRequest) GetCommissionPercent() string {
	if x != nil {
		return x.CommissionPercent
	}
	return ""
}

type SetDefaultTariffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TariffId      int64                  `protobuf:"varint,1,opt,name=tariff_id,json=tariffId,proto3" json:"tariff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultTariffRequest) Reset() {
	*x = SetDefaultTariffRequest{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultTariffRequest) ProtoMessage() {}

func (x *SetDefaultTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultTariffRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultTariffRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetDefaultTariffRequest) GetTariffId() int64 {
	if x != nil {
		return x.TariffId
	}
	return 0
}

type AssignVendorTariffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	TariffId      int64                  `protobuf:"varint,2,opt,name=tariff_id,json=tariffId,proto3" json:"tariff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignVendorTariffRequest) Reset() {
	*x = AssignVendorTariffRequest{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVendorTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVendorTariffRequest) ProtoMessage() {}

func (x *AssignVendorTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVendorTariffRequest.ProtoReflect.Descriptor instead.
func (*AssignVendorTariffRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *AssignVendorTariffRequest) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *AssignVendorTariffRequest) GetTariffId() int64 {
	if x != nil {
		return x.TariffId
	}
	return 0
}

type GetVendorTariffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendorTariffRequest) Reset() {
	*x = GetVendorTariffRequest{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorTariffRequest) ProtoMessage() {}

func (x *GetVendorTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorTariffRequest.ProtoReflect.Descriptor instead.
func (*GetVendorTariffRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetVendorTariffRequest) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

type TariffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tariff        *Tariff                `protobuf:"bytes,1,opt,name=tariff,proto3" json:"tariff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TariffResponse) Reset() {
	*x = TariffResponse{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TariffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffResponse) ProtoMessage() {}

func (x *TariffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffResponse.ProtoReflect.Descriptor instead.
func (*TariffResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *TariffResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type VendorTariffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Tariff        *Tariff                `protobuf:"bytes,2,opt,name=tariff,proto3" json:"tariff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorTariffResponse) Reset() {
	*x = VendorTariffResponse{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorTariffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorTariffResponse) ProtoMessage() {}

func (x *VendorTariffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorTariffResponse.ProtoReflect.Descriptor instead.
func (*VendorTariffResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *VendorTariffResponse) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *VendorTariffResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type Tariff struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommissionPercent string                 `protobuf:"bytes,3,opt,name=commission_percent,json=commissionPercent,proto3" json:"commission_percent,omitempty"`
	IsDefault         bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	AssignedVendors   int64                  `protobuf:"varint,5,opt,name=assigned_vendors,json=assignedVendors,proto3" json:"assigned_vendors,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Tariff) Reset() {
	*x = Tariff{}
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tariff) ProtoMessage() {}

func (x *Tariff) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_analytics_admin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tariff.ProtoReflect.Descriptor instead.
func (*Tariff) Descriptor() ([]byte, []int) {
	return file_v1_admin_analytics_admin_service_proto_rawDescGZIP(), []int{9}
}

func (x *Tariff) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tariff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tariff) GetCommissionPercent() string {
	if x != nil {
		return x.CommissionPercent
	}
	return ""
}

func (x *Tariff) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Tariff) GetAssignedVendors() int64 {
	if x != nil {
		return x.AssignedVendors
	}
	return 0
}

func (x *Tariff) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tariff) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_v1_admin_analytics_admin_service_proto protoreflect.FileDescriptor

const file_v1_admin_analytics_admin_service_proto_rawDesc = "" +
	"\n" +
	"&v1/admin/analytics_admin_service.proto\x12;github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin\"\x14\n" +
	"\x12ListTariffsRequest\"t\n" +
	"\x13ListTariffsResponse\x12]\n" +
	"\atariffs\x18\x01 \x03(\v2C.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffR\atariffs\"X\n" +
	"\x13CreateTariffRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x12commission_percent\x18\x02 \x01(\tR\x11commissionPercent\"u\n" +
	"\x13UpdateTariffRequest\x12\x1b\n" +
	"\ttariff_id\x18\x01 \x01(\x03R\btariffId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12commission_percent\x18\x03 \x01(\tR\x11commissionPercent\"6\n" +
	"\x17SetDefaultTariffRequest\x12\x1b\n" +
	"\ttariff_id\x18\x01 \x01(\x03R\btariffId\"U\n" +
	"\x19AssignVendorTariffRequest\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\x12\x1b\n" +
	"\ttariff_id\x18\x02 \x01(\x03R\btariffId\"5\n" +
	"\x16GetVendorTariffRequest\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\"m\n" +
	"\x0eTariffResponse\x12[\n" +
	"\x06tariff\x18\x01 \x01(\v2C.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffR\x06tariff\"\x90\x01\n" +
	"\x14VendorTariffResponse\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\x12[\n" +
	"\x06tariff\x18\x02 \x01(\v2C.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffR\x06tariff\"\xe3\x01\n" +
	"\x06Tariff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12commission_percent\x18\x03 \x01(\tR\x11commissionPercent\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x12)\n" +
	"\x10assigned_vendors\x18\x05 \x01(\x03R\x0fassignedVendors\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt2\xe0\b\n" +
	"\x15AnalyticsAdminService\x12\xb0\x01\n" +
	"\vListTariffs\x12O.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsRequest\x1aP.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsResponse\x12\xad\x01\n" +
	"\fCreateTariff\x12P.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.CreateTariffRequest\x1aK.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse\x12\xad\x01\n" +
	"\fUpdateTariff\x12P.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.UpdateTariffRequest\x1aK.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse\x12\xb5\x01\n" +
	"\x10SetDefaultTariff\x12T.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.SetDefaultTariffRequest\x1aK.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse\x12\xbf\x01\n" +
	"\x12AssignVendorTariff\x12V.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AssignVendorTariffRequest\x1aQ.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.VendorTariffResponse\x12\xb9\x01\n" +
	"\x0fGetVendorTariff\x12S.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.GetVendorTariffRequest\x1aQ.github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.VendorTariffResponseBCZAgithub.com/martketplace-vkr/analytics/pkg/api/grpc/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_analytics_admin_service_proto_rawDescOnce sync.Once
	file_v1_admin_analytics_admin_service_proto_rawDescData []byte
)

func file_v1_admin_analytics_admin_service_proto_rawDescGZIP() []byte {
	file_v1_admin_analytics_admin_service_proto_rawDescOnce.Do(func() {
		file_v1_admin_analytics_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_analytics_admin_service_proto_rawDesc), len(file_v1_admin_analytics_admin_service_proto_rawDesc)))
	})
	return file_v1_admin_analytics_admin_service_proto_rawDescData
}

var file_v1_admin_analytics_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_admin_analytics_admin_service_proto_goTypes = []any{
	(*ListTariffsRequest)(nil),        // 0: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsRequest
	(*ListTariffsResponse)(nil),       // 1: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsResponse
	(*CreateTariffRequest)(nil),       // 2: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.CreateTariffRequest
	(*UpdateTariffRequest)(nil),       // 3: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.UpdateTariffRequest
	(*SetDefaultTariffRequest)(nil),   // 4: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.SetDefaultTariffRequest
	(*AssignVendorTariffRequest)(nil), // 5: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AssignVendorTariffRequest
	(*GetVendorTariffRequest)(nil),    // 6: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.GetVendorTariffRequest
	(*TariffResponse)(nil),            // 7: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse
	(*VendorTariffResponse)(nil),      // 8: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.VendorTariffResponse
	(*Tariff)(nil),                    // 9: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.Tariff
}
var file_v1_admin_analytics_admin_service_proto_depIdxs = []int32{
	9, // 0: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsResponse.tariffs:type_name -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.Tariff
	9, // 1: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse.tariff:type_name -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.Tariff
	9, // 2: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.VendorTariffResponse.tariff:type_name -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.Tariff
	0, // 3: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.ListTariffs:input_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsRequest
	2, // 4: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.CreateTariff:input_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.CreateTariffRequest
	3, // 5: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.UpdateTariff:input_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.UpdateTariffRequest
	4, // 6: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.SetDefaultTariff:input_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.SetDefaultTariffRequest
	5, // 7: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.AssignVendorTariff:input_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AssignVendorTariffRequest
	6, // 8: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.GetVendorTariff:input_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.GetVendorTariffRequest
	1, // 9: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.ListTariffs:output_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.ListTariffsResponse
	7, // 10: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.CreateTariff:output_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse
	7, // 11: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.UpdateTariff:output_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse
	7, // 12: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.SetDefaultTariff:output_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.TariffResponse
	8, // 13: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.AssignVendorTariff:output_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.VendorTariffResponse
	8, // 14: github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.AnalyticsAdminService.GetVendorTariff:output_type -> github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin.VendorTariffResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_admin_analytics_admin_service_proto_init() }
func file_v1_admin_analytics_admin_service_proto_init() {
	if File_v1_admin_analytics_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_analytics_admin_service_proto_rawDesc), len(file_v1_admin_analytics_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_analytics_admin_service_proto_goTypes,
		DependencyIndexes: file_v1_admin_analytics_admin_service_proto_depIdxs,
		MessageInfos:      file_v1_admin_analytics_admin_service_proto_msgTypes,
	}.Build()
	File_v1_admin_analytics_admin_service_proto = out.File
	file_v1_admin_analytics_admin_service_proto_goTypes = nil
	file_v1_admin_analytics_admin_service_proto_depIdxs = nil
}
