syntax = "proto3";

package github.com.martketplace.vkr.analytics.pkg.api.grpc.v1.admin;

option go_package = "github.com/martketplace-vkr/analytics/pkg/api/grpc/v1/admin;admin";

service AnalyticsAdminService {
  rpc ListTariffs(ListTariffsRequest) returns (ListTariffsResponse);
  rpc CreateTariff(CreateTariffRequest) returns (TariffResponse);
  rpc UpdateTariff(UpdateTariffRequest) returns (TariffResponse);
  rpc SetDefaultTariff(SetDefaultTariffRequest) returns (TariffResponse);
  rpc AssignVendorTariff(AssignVendorTariffRequest) returns (VendorTariffResponse);
  rpc GetVendorTariff(GetVendorTariffRequest) returns (VendorTariffResponse);
}

message ListTariffsRequest {}

message ListTariffsResponse {
  repeated Tariff tariffs = 1;
}

message CreateTariffRequest {
  string name = 1;
  string commission_percent = 2;
}

message UpdateTariffRequest {
  int64 tariff_id = 1;
  string name = 2;
  string commission_percent = 3;
}

message SetDefaultTariffRequest {
  int64 tariff_id = 1;
}

message AssignVendorTariffRequest {
  int64 vendor_id = 1;
  int64 tariff_id = 2;
}

message GetVendorTariffRequest {
  int64 vendor_id = 1;
}

message TariffResponse {
  Tariff tariff = 1;
}

message VendorTariffResponse {
  int64 vendor_id = 1;
  Tariff tariff = 2;
}

message Tariff {
  int64 id = 1;
  string name = 2;
  string commission_percent = 3;
  bool is_default = 4;
  int64 assigned_vendors = 5;
  string created_at = 6;
  string updated_at = 7;
}
